package com.github.throyer.todoapp.views;

import com.github.throyer.todoapp.infra.ui.Views;
import com.github.throyer.todoapp.infra.ui.ViewManager;
import com.github.throyer.todoapp.domain.exceptions.IncorrectCredentialsException;
import com.github.throyer.todoapp.domain.models.Session;
import com.github.throyer.todoapp.infra.ui.View;
import com.github.throyer.todoapp.utils.Icons;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import org.springframework.stereotype.Component;

@Component
public class Login extends View {
    private final Session session;
    
    public Login(Session session) {        
        this.session = session;
        
        initComponents();
        
        var list = Icons.icon(
            FontAwesome.LIST,
            45,
            new Color(160, 160, 160)
        );
        
        labelIconList.setIcon(list);

        labelIconCheck.setIcon(Icons.icon(
            FontAwesome.CHECK,
            25,
            new Color(160, 160, 160)
        ));
        
        Icons.toImage(list);
        
        setIconImage(Icons.toImage(list));
        setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconsContainer = new javax.swing.JPanel();
        labelIconList = new javax.swing.JLabel();
        labelIconCheck = new javax.swing.JLabel();
        formContainer = new javax.swing.JPanel();
        titleContainer = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelEmail = new javax.swing.JPanel();
        emailSpaceLeft = new javax.swing.JPanel();
        labelIconUser = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        emailSpaceRight = new javax.swing.JPanel();
        panelPassword = new javax.swing.JPanel();
        passwordSpaceLeft = new javax.swing.JPanel();
        labelIconPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        passwordSpaceRight = new javax.swing.JPanel();
        separator = new javax.swing.JSeparator();
        buttonContainer = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(330, 152));
        setName("Login"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(330, 152));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        iconsContainer.setLayout(new javax.swing.BoxLayout(iconsContainer, javax.swing.BoxLayout.LINE_AXIS));

        labelIconList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIconList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iconsContainer.add(labelIconList);

        labelIconCheck.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        iconsContainer.add(labelIconCheck);

        getContentPane().add(iconsContainer);

        formContainer.setLayout(new javax.swing.BoxLayout(formContainer, javax.swing.BoxLayout.Y_AXIS));

        titleContainer.setLayout(new javax.swing.BoxLayout(titleContainer, javax.swing.BoxLayout.LINE_AXIS));

        labelTitle.setText("Gerenciador de Tarefas");
        labelTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        titleContainer.add(labelTitle);

        formContainer.add(titleContainer);

        panelEmail.setLayout(new javax.swing.BoxLayout(panelEmail, javax.swing.BoxLayout.X_AXIS));

        emailSpaceLeft.setMaximumSize(new java.awt.Dimension(10, 25));
        emailSpaceLeft.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout emailSpaceLeftLayout = new javax.swing.GroupLayout(emailSpaceLeft);
        emailSpaceLeft.setLayout(emailSpaceLeftLayout);
        emailSpaceLeftLayout.setHorizontalGroup(
            emailSpaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        emailSpaceLeftLayout.setVerticalGroup(
            emailSpaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelEmail.add(emailSpaceLeft);

        IconFontSwing.register(FontAwesome.getIconFont());
        Icon iu = IconFontSwing.buildIcon(FontAwesome.USER, 20);
        labelIconUser.setIcon(iu);
        panelEmail.add(labelIconUser);

        inputEmail.setMaximumSize(new java.awt.Dimension(200, 25));
        inputEmail.setMinimumSize(new java.awt.Dimension(200, 25));
        inputEmail.setPreferredSize(new java.awt.Dimension(200, 25));
        panelEmail.add(inputEmail);

        emailSpaceRight.setMaximumSize(new java.awt.Dimension(10, 25));
        emailSpaceRight.setMinimumSize(new java.awt.Dimension(10, 25));
        emailSpaceRight.setPreferredSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout emailSpaceRightLayout = new javax.swing.GroupLayout(emailSpaceRight);
        emailSpaceRight.setLayout(emailSpaceRightLayout);
        emailSpaceRightLayout.setHorizontalGroup(
            emailSpaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        emailSpaceRightLayout.setVerticalGroup(
            emailSpaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelEmail.add(emailSpaceRight);

        formContainer.add(panelEmail);

        panelPassword.setLayout(new javax.swing.BoxLayout(panelPassword, javax.swing.BoxLayout.LINE_AXIS));

        passwordSpaceLeft.setMaximumSize(new java.awt.Dimension(10, 25));
        passwordSpaceLeft.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout passwordSpaceLeftLayout = new javax.swing.GroupLayout(passwordSpaceLeft);
        passwordSpaceLeft.setLayout(passwordSpaceLeftLayout);
        passwordSpaceLeftLayout.setHorizontalGroup(
            passwordSpaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        passwordSpaceLeftLayout.setVerticalGroup(
            passwordSpaceLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelPassword.add(passwordSpaceLeft);

        IconFontSwing.register(FontAwesome.getIconFont());
        Icon ip = IconFontSwing.buildIcon(FontAwesome.LOCK, 20);
        labelIconPassword.setIcon(ip);
        panelPassword.add(labelIconPassword);

        inputPassword.setMaximumSize(new java.awt.Dimension(200, 25));
        inputPassword.setMinimumSize(new java.awt.Dimension(200, 25));
        inputPassword.setPreferredSize(new java.awt.Dimension(200, 25));
        panelPassword.add(inputPassword);

        passwordSpaceRight.setMaximumSize(new java.awt.Dimension(10, 25));
        passwordSpaceRight.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout passwordSpaceRightLayout = new javax.swing.GroupLayout(passwordSpaceRight);
        passwordSpaceRight.setLayout(passwordSpaceRightLayout);
        passwordSpaceRightLayout.setHorizontalGroup(
            passwordSpaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        passwordSpaceRightLayout.setVerticalGroup(
            passwordSpaceRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        panelPassword.add(passwordSpaceRight);

        formContainer.add(panelPassword);

        getContentPane().add(formContainer);
        getContentPane().add(separator);

        buttonContainer.setLayout(new javax.swing.BoxLayout(buttonContainer, javax.swing.BoxLayout.LINE_AXIS));

        closeButton.setText("Fechar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickClose(evt);
            }
        });
        buttonContainer.add(closeButton);

        loginButton.setText("Entrar");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickLogin(evt);
            }
        });
        buttonContainer.add(loginButton);

        registerButton.setText("Registrar");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickRegister(evt);
            }
        });
        buttonContainer.add(registerButton);

        getContentPane().add(buttonContainer);

        setSize(new java.awt.Dimension(346, 191));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onClickClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickClose
        System.exit(FINALIZACAO_CONTROLADA);
    }//GEN-LAST:event_onClickClose

    private void onClickLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickLogin
        handleLogin(inputEmail.getText(), String.valueOf(inputPassword.getPassword()));
    }//GEN-LAST:event_onClickLogin

    private void onClickRegister(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickRegister
        handleNavigateToCreateUserView();
    }//GEN-LAST:event_onClickRegister

    private void handleLogin(String email, String password) {
        try {
            
            session.login(email, password);
            ViewManager.navigate(Views.LOGIN, Views.TASK_MANAGER);
            
        } catch (IncorrectCredentialsException exception) {
            
            JOptionPane.showMessageDialog(
                new JFrame("Problema de autorização"),
                "email ou senha invalido"
            );
        }
    }

    private void handleNavigateToCreateUserView() {
        ViewManager.navigate(Views.LOGIN, Views.CREATE_USER);
    }
        
    private final int FINALIZACAO_CONTROLADA = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel emailSpaceLeft;
    private javax.swing.JPanel emailSpaceRight;
    private javax.swing.JPanel formContainer;
    private javax.swing.JPanel iconsContainer;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel labelIconCheck;
    private javax.swing.JLabel labelIconList;
    private javax.swing.JLabel labelIconPassword;
    private javax.swing.JLabel labelIconUser;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelEmail;
    private javax.swing.JPanel panelPassword;
    private javax.swing.JPanel passwordSpaceLeft;
    private javax.swing.JPanel passwordSpaceRight;
    private javax.swing.JButton registerButton;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel titleContainer;
    // End of variables declaration//GEN-END:variables
}
