/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.comp2028.todosapp.views;

import br.edu.unifil.comp2028.todosapp.entidades.Usuario;
import br.edu.unifil.comp2028.todosapp.entidades.Tarefa;

import br.edu.unifil.comp2028.todosapp.dao.TarefaDAO;
import java.awt.Image;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import javax.swing.JFrame;

/**
 *
 * @author Renato
 */
public class JFrameAdicionarTrarefas extends javax.swing.JFrame {

    /**
     * Creates new form frameAdicionarTrarefas
     */
    public JFrameAdicionarTrarefas(Usuario usuario, Image img) {
        this.img = img;
        setIconImage(img);
        this.usuario = usuario;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        PanelDescFrame = new javax.swing.JPanel();
        LabelDescFrame = new javax.swing.JLabel();
        SeparatorTop = new javax.swing.JSeparator();
        PanelInfoTarefa = new javax.swing.JPanel();
        PanelDescricao = new javax.swing.JPanel();
        PanelEspaceEsq = new javax.swing.JPanel();
        LabelDescricao = new javax.swing.JLabel();
        TextFieldDescricao = new javax.swing.JTextField();
        PanelEspaceDir = new javax.swing.JPanel();
        PanelEspaceInfo = new javax.swing.JPanel();
        PanelDateTimeCategories = new javax.swing.JPanel();
        PanelCategoriesPick = new javax.swing.JPanel();
        PanelDateTimeInfo = new javax.swing.JPanel();
        LabelDateTimeInfo = new javax.swing.JLabel();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        PanelCaregoriesInfo = new javax.swing.JPanel();
        LabelCategories = new javax.swing.JLabel();
        PanelTableCategories = new javax.swing.JPanel();
        scroller = new javax.swing.JScrollPane();
        TableCaregorias = new javax.swing.JTable();
        PanelEditarCategorias = new javax.swing.JPanel();
        ButtonEditarCategorias = new javax.swing.JButton();
        SeparatorBot = new javax.swing.JSeparator();
        PanelButtons = new javax.swing.JPanel();
        ButtonCancelar = new javax.swing.JButton();
        ButtonAdicionar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        PanelDescFrame.setLayout(new javax.swing.BoxLayout(PanelDescFrame, javax.swing.BoxLayout.LINE_AXIS));

        LabelDescFrame.setText("Adicionar tarefa");
        PanelDescFrame.add(LabelDescFrame);

        getContentPane().add(PanelDescFrame);

        SeparatorTop.setMinimumSize(new java.awt.Dimension(0, 10));
        SeparatorTop.setPreferredSize(new java.awt.Dimension(0, 10));
        getContentPane().add(SeparatorTop);

        PanelInfoTarefa.setLayout(new javax.swing.BoxLayout(PanelInfoTarefa, javax.swing.BoxLayout.Y_AXIS));

        PanelDescricao.setLayout(new javax.swing.BoxLayout(PanelDescricao, javax.swing.BoxLayout.LINE_AXIS));

        PanelEspaceEsq.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout PanelEspaceEsqLayout = new javax.swing.GroupLayout(PanelEspaceEsq);
        PanelEspaceEsq.setLayout(PanelEspaceEsqLayout);
        PanelEspaceEsqLayout.setHorizontalGroup(
            PanelEspaceEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelEspaceEsqLayout.setVerticalGroup(
            PanelEspaceEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        PanelDescricao.add(PanelEspaceEsq);

        LabelDescricao.setText("Descrição: ");
        PanelDescricao.add(LabelDescricao);

        TextFieldDescricao.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        TextFieldDescricao.setMinimumSize(new java.awt.Dimension(6, 30));
        TextFieldDescricao.setPreferredSize(new java.awt.Dimension(6, 30));
        PanelDescricao.add(TextFieldDescricao);

        PanelEspaceDir.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout PanelEspaceDirLayout = new javax.swing.GroupLayout(PanelEspaceDir);
        PanelEspaceDir.setLayout(PanelEspaceDirLayout);
        PanelEspaceDirLayout.setHorizontalGroup(
            PanelEspaceDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelEspaceDirLayout.setVerticalGroup(
            PanelEspaceDirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        PanelDescricao.add(PanelEspaceDir);

        PanelInfoTarefa.add(PanelDescricao);

        PanelEspaceInfo.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout PanelEspaceInfoLayout = new javax.swing.GroupLayout(PanelEspaceInfo);
        PanelEspaceInfo.setLayout(PanelEspaceInfoLayout);
        PanelEspaceInfoLayout.setHorizontalGroup(
            PanelEspaceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        PanelEspaceInfoLayout.setVerticalGroup(
            PanelEspaceInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelInfoTarefa.add(PanelEspaceInfo);

        PanelDateTimeCategories.setLayout(new javax.swing.BoxLayout(PanelDateTimeCategories, javax.swing.BoxLayout.LINE_AXIS));

        PanelCategoriesPick.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelCategoriesPick.setLayout(new javax.swing.BoxLayout(PanelCategoriesPick, javax.swing.BoxLayout.Y_AXIS));

        PanelDateTimeInfo.setLayout(new javax.swing.BoxLayout(PanelDateTimeInfo, javax.swing.BoxLayout.LINE_AXIS));

        LabelDateTimeInfo.setText("Selecione uma data e um horario");
        PanelDateTimeInfo.add(LabelDateTimeInfo);

        PanelCategoriesPick.add(PanelDateTimeInfo);

        dateTimePicker1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        dateTimePicker1.setMinimumSize(new java.awt.Dimension(240, 30));
        dateTimePicker1.setPreferredSize(new java.awt.Dimension(240, 30));
        PanelCategoriesPick.add(dateTimePicker1);

        PanelCaregoriesInfo.setLayout(new javax.swing.BoxLayout(PanelCaregoriesInfo, javax.swing.BoxLayout.LINE_AXIS));

        LabelCategories.setText("Selecione uma ou mais categorias para sua tarefa");
        PanelCaregoriesInfo.add(LabelCategories);

        PanelCategoriesPick.add(PanelCaregoriesInfo);

        PanelTableCategories.setLayout(new javax.swing.BoxLayout(PanelTableCategories, javax.swing.BoxLayout.LINE_AXIS));

        TableCaregorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Categoria", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroller.setViewportView(TableCaregorias);
        if (TableCaregorias.getColumnModel().getColumnCount() > 0) {
            TableCaregorias.getColumnModel().getColumn(0).setResizable(false);
            TableCaregorias.getColumnModel().getColumn(1).setResizable(false);
        }

        PanelTableCategories.add(scroller);

        PanelCategoriesPick.add(PanelTableCategories);

        PanelEditarCategorias.setLayout(new javax.swing.BoxLayout(PanelEditarCategorias, javax.swing.BoxLayout.LINE_AXIS));

        ButtonEditarCategorias.setText("Editar categorias");
        ButtonEditarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditarCategoriasActionPerformed(evt);
            }
        });
        PanelEditarCategorias.add(ButtonEditarCategorias);

        PanelCategoriesPick.add(PanelEditarCategorias);

        PanelDateTimeCategories.add(PanelCategoriesPick);

        PanelInfoTarefa.add(PanelDateTimeCategories);

        getContentPane().add(PanelInfoTarefa);

        SeparatorBot.setMinimumSize(new java.awt.Dimension(0, 10));
        SeparatorBot.setPreferredSize(new java.awt.Dimension(0, 10));
        getContentPane().add(SeparatorBot);

        PanelButtons.setLayout(new javax.swing.BoxLayout(PanelButtons, javax.swing.BoxLayout.LINE_AXIS));

        ButtonCancelar.setText("Voltar");
        ButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarActionPerformed(evt);
            }
        });
        PanelButtons.add(ButtonCancelar);

        ButtonAdicionar.setText("Adicionar");
        ButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdicionarActionPerformed(evt);
            }
        });
        PanelButtons.add(ButtonAdicionar);

        getContentPane().add(PanelButtons);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEditarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditarCategoriasActionPerformed
        // TODO add your handling code here:
        JFrameEditarCategorias categorias = new JFrameEditarCategorias(usuario, img);
        categorias.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonEditarCategoriasActionPerformed

    private void ButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonCancelarActionPerformed
        // TODO add your handling code here:
        JFrameTarefas tarefas = new JFrameTarefas(usuario, img);
        tarefas.setVisible(true);
        dispose();
    }// GEN-LAST:event_ButtonCancelarActionPerformed

    private void ButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonAdicionarActionPerformed
        // TODO add your handling code here:

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("todosappPU");

        TarefaDAO tarefaDAO = new TarefaDAO(emf);

        Tarefa tarefa = new Tarefa();

        // Descrição
        tarefa.setDescricao(TextFieldDescricao.getText());

        // Prazo
        int dia = dateTimePicker1.getDatePicker().getDate().getDayOfMonth();
        int mes = dateTimePicker1.getDatePicker().getDate().getMonthValue();
        int ano = dateTimePicker1.getDatePicker().getDate().getYear();

        String time = dateTimePicker1.getTimePicker().getText();

        String data = ano + "/" + mes + "/" + dia + " " + time + ":00";

        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");

        try {
            Date prazo;
            prazo = simpleDateFormat.parse(data);
            tarefa.setPrazo(prazo);
        } catch (ParseException ex) {

            Logger.getLogger(JFrameAdicionarTrarefas.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Status
        tarefa.setStatus(false);

        // Usuario criador
        tarefa.setUsuarioId(usuario);

        // Inserindo tarefa no banco
        tarefaDAO.create(tarefa);

        JFrameTarefas tarefas = new JFrameTarefas(usuario, img);
        tarefas.setVisible(true);

        dispose();
    }// GEN-LAST:event_ButtonAdicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdicionar;
    private javax.swing.JButton ButtonCancelar;
    private javax.swing.JButton ButtonEditarCategorias;
    private javax.swing.JLabel LabelCategories;
    private javax.swing.JLabel LabelDateTimeInfo;
    private javax.swing.JLabel LabelDescFrame;
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelCaregoriesInfo;
    private javax.swing.JPanel PanelCategoriesPick;
    private javax.swing.JPanel PanelDateTimeCategories;
    private javax.swing.JPanel PanelDateTimeInfo;
    private javax.swing.JPanel PanelDescFrame;
    private javax.swing.JPanel PanelDescricao;
    private javax.swing.JPanel PanelEditarCategorias;
    private javax.swing.JPanel PanelEspaceDir;
    private javax.swing.JPanel PanelEspaceEsq;
    private javax.swing.JPanel PanelEspaceInfo;
    private javax.swing.JPanel PanelInfoTarefa;
    private javax.swing.JPanel PanelTableCategories;
    private javax.swing.JSeparator SeparatorBot;
    private javax.swing.JSeparator SeparatorTop;
    private javax.swing.JTable TableCaregorias;
    private javax.swing.JTextField TextFieldDescricao;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane scroller;
    // End of variables declaration//GEN-END:variables
    private final Usuario usuario;
    private static Image img;
}
