/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.comp2028.todosapp.views;

import br.edu.unifil.comp2028.todosapp.dao.UsuarioDAO;
import br.edu.unifil.comp2028.todosapp.entidades.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import resource.IconResource;

/**
 *
 * @author Renato
 */
public class JFrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form frameLogin
     */
    public JFrameLogin() {
        initComponents();
        definirIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIcons = new javax.swing.JPanel();
        labelIcon1 = new javax.swing.JLabel();
        labelIcon2 = new javax.swing.JLabel();
        logPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelUser = new javax.swing.JPanel();
        espUesq = new javax.swing.JPanel();
        u = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        espUdir = new javax.swing.JPanel();
        PanelSenha = new javax.swing.JPanel();
        espSesq = new javax.swing.JPanel();
        p = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        espSdir = new javax.swing.JPanel();
        separador = new javax.swing.JSeparator();
        PanelButtons = new javax.swing.JPanel();
        buttonFechar = new javax.swing.JButton();
        buttonEntrar = new javax.swing.JButton();
        buttonRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(330, 152));
        setMinimumSize(new java.awt.Dimension(330, 152));
        setName("Login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(330, 152));
        setResizable(false);
        setSize(new java.awt.Dimension(330, 152));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelIcons.setLayout(new javax.swing.BoxLayout(panelIcons, javax.swing.BoxLayout.LINE_AXIS));

        labelIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panelIcons.add(labelIcon1);

        labelIcon2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        panelIcons.add(labelIcon2);

        getContentPane().add(panelIcons);

        logPanel.setLayout(new javax.swing.BoxLayout(logPanel, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Gerenciador de Tarefas");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.add(jLabel1);

        logPanel.add(jPanel2);

        PanelUser.setLayout(new javax.swing.BoxLayout(PanelUser, javax.swing.BoxLayout.X_AXIS));

        espUesq.setMaximumSize(new java.awt.Dimension(10, 25));
        espUesq.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout espUesqLayout = new javax.swing.GroupLayout(espUesq);
        espUesq.setLayout(espUesqLayout);
        espUesqLayout.setHorizontalGroup(
            espUesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espUesqLayout.setVerticalGroup(
            espUesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        PanelUser.add(espUesq);

        IconFontSwing.register(FontAwesome.getIconFont());
        Icon iu = IconFontSwing.buildIcon(FontAwesome.USER, 20);
        u.setIcon(iu);
        PanelUser.add(u);

        user.setMaximumSize(new java.awt.Dimension(200, 25));
        user.setMinimumSize(new java.awt.Dimension(200, 25));
        user.setPreferredSize(new java.awt.Dimension(200, 25));
        PanelUser.add(user);

        espUdir.setMaximumSize(new java.awt.Dimension(10, 25));
        espUdir.setMinimumSize(new java.awt.Dimension(10, 25));
        espUdir.setPreferredSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout espUdirLayout = new javax.swing.GroupLayout(espUdir);
        espUdir.setLayout(espUdirLayout);
        espUdirLayout.setHorizontalGroup(
            espUdirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espUdirLayout.setVerticalGroup(
            espUdirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        PanelUser.add(espUdir);

        logPanel.add(PanelUser);

        PanelSenha.setLayout(new javax.swing.BoxLayout(PanelSenha, javax.swing.BoxLayout.LINE_AXIS));

        espSesq.setMaximumSize(new java.awt.Dimension(10, 25));
        espSesq.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout espSesqLayout = new javax.swing.GroupLayout(espSesq);
        espSesq.setLayout(espSesqLayout);
        espSesqLayout.setHorizontalGroup(
            espSesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espSesqLayout.setVerticalGroup(
            espSesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        PanelSenha.add(espSesq);

        IconFontSwing.register(FontAwesome.getIconFont());
        Icon ip = IconFontSwing.buildIcon(FontAwesome.LOCK, 20);
        p.setIcon(ip);
        PanelSenha.add(p);

        senha.setMaximumSize(new java.awt.Dimension(200, 25));
        senha.setMinimumSize(new java.awt.Dimension(200, 25));
        senha.setPreferredSize(new java.awt.Dimension(200, 25));
        PanelSenha.add(senha);

        espSdir.setMaximumSize(new java.awt.Dimension(10, 25));
        espSdir.setMinimumSize(new java.awt.Dimension(10, 25));

        javax.swing.GroupLayout espSdirLayout = new javax.swing.GroupLayout(espSdir);
        espSdir.setLayout(espSdirLayout);
        espSdirLayout.setHorizontalGroup(
            espSdirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espSdirLayout.setVerticalGroup(
            espSdirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        PanelSenha.add(espSdir);

        logPanel.add(PanelSenha);

        getContentPane().add(logPanel);
        getContentPane().add(separador);

        PanelButtons.setLayout(new javax.swing.BoxLayout(PanelButtons, javax.swing.BoxLayout.LINE_AXIS));

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });
        PanelButtons.add(buttonFechar);

        buttonEntrar.setText("Entrar");
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });
        PanelButtons.add(buttonEntrar);

        buttonRegistrar.setText("Registrar");
        buttonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarActionPerformed(evt);
            }
        });
        PanelButtons.add(buttonRegistrar);

        getContentPane().add(PanelButtons);

        setSize(new java.awt.Dimension(346, 191));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        // TODO add your handling code here:
        System.exit(FINALIZACAO_CONTROLADA);
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEntrarActionPerformed
        // TODO add your handling code here:
        logar(user.getText(), senha.getText());
    }//GEN-LAST:event_buttonEntrarActionPerformed

    private void buttonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarActionPerformed
        // TODO add your handling code here:
        criarUsuario();
    }//GEN-LAST:event_buttonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLogin().setVisible(true);
            }
        });
    }

    public void logar(String user, String senha) {

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("todosappPU");

        UsuarioDAO usuarioDAO = new UsuarioDAO(emf);

        Usuario usuario = usuarioDAO.findUsuarioUsername(user);

        emf.close();

        JFrame frame = new JFrame("Problema de autentifição");

        if (usuario == null) {

            JOptionPane.showMessageDialog(frame, "Usuario invalido");

        } else {
            if (usuario.getPassword().equals(senha)) {
                JFrameTarefas tarefas = new JFrameTarefas(usuario, img);
                tarefas.setVisible(true);
                dispose();
            } else {

                JOptionPane.showMessageDialog(frame, "Senha incorreta");

            }
        }

    }

    private void criarUsuario() {
        JFrameCriarUsuario criarUsuario = new JFrameCriarUsuario(img);
        criarUsuario.setVisible(true);
        dispose();
    }
    
    private void definirIcone() {
        IconFontSwing.register(FontAwesome.getIconFont());
        Icon icon1 = IconFontSwing.buildIcon(FontAwesome.LIST, 45, new Color(160, 160, 160));
        Icon icon2 = IconFontSwing.buildIcon(FontAwesome.CHECK, 25, new Color(160, 160, 160));
        labelIcon1.setIcon(icon1);
        labelIcon2.setIcon(icon2);
        img = IRC.iconToImage(icon1);
        setIconImage(img);
        setTitle("Login");
    }
    private IconResource IRC = new IconResource();
    private final int FINALIZACAO_CONTROLADA = 0;
    private static Image img;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelSenha;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JButton buttonRegistrar;
    private javax.swing.JPanel espSdir;
    private javax.swing.JPanel espSesq;
    private javax.swing.JPanel espUdir;
    private javax.swing.JPanel espUesq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIcon1;
    private javax.swing.JLabel labelIcon2;
    private javax.swing.JPanel logPanel;
    private javax.swing.JLabel p;
    private javax.swing.JPanel panelIcons;
    private javax.swing.JPasswordField senha;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel u;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
