/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.comp2028.todosapp.views;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import br.edu.unifil.comp2028.todosapp.dao.UsuarioDAO;
import br.edu.unifil.comp2028.todosapp.entidades.Usuario;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author Renato
 */
public class JFrameCriarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frameCriarUsuario
     */
    public JFrameCriarUsuario(Image img) {
        this.img = img;
        setIconImage(img);
        IconFontSwing.register(FontAwesome.getIconFont());
        iconTrue = IconFontSwing.buildIcon(FontAwesome.CHECK, 35, new Color(0, 100, 0));
        iconFalse = IconFontSwing.buildIcon(FontAwesome.TIMES, 35, new Color(255, 0, 0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeral = new javax.swing.JPanel();
        panelInfoFrame = new javax.swing.JPanel();
        LabelInfoFrame = new javax.swing.JLabel();
        Puser = new javax.swing.JPanel();
        LabeluserInfo = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        PDisponibilidade = new javax.swing.JPanel();
        userNameStatus = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        Psenha = new javax.swing.JPanel();
        LabelSenhaInfo = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        PrepeteSenha = new javax.swing.JPanel();
        LabeRepetirSenhaInfo = new javax.swing.JLabel();
        repeteSenha = new javax.swing.JPasswordField();
        PanelButtons = new javax.swing.JPanel();
        ButtonVoltar = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        PanelGeral.setLayout(new javax.swing.BoxLayout(PanelGeral, javax.swing.BoxLayout.Y_AXIS));

        panelInfoFrame.setLayout(new javax.swing.BoxLayout(panelInfoFrame, javax.swing.BoxLayout.LINE_AXIS));

        LabelInfoFrame.setText("Adicionar Usuario");
        panelInfoFrame.add(LabelInfoFrame);

        PanelGeral.add(panelInfoFrame);

        Puser.setLayout(new javax.swing.BoxLayout(Puser, javax.swing.BoxLayout.LINE_AXIS));

        LabeluserInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabeluserInfo.setText("Criar um nome de usuário:");
        LabeluserInfo.setMaximumSize(new java.awt.Dimension(170, 14));
        LabeluserInfo.setMinimumSize(new java.awt.Dimension(170, 14));
        LabeluserInfo.setPreferredSize(new java.awt.Dimension(170, 14));
        Puser.add(LabeluserInfo);

        user.setMaximumSize(new java.awt.Dimension(230, 25));
        user.setMinimumSize(new java.awt.Dimension(230, 25));
        user.setPreferredSize(new java.awt.Dimension(230, 25));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        Puser.add(user);

        PanelGeral.add(Puser);

        userNameStatus.setForeground(new java.awt.Color(0, 102, 51));
        userNameStatus.setToolTipText("");
        userNameStatus.setMaximumSize(new java.awt.Dimension(200, 20));
        userNameStatus.setMinimumSize(new java.awt.Dimension(200, 20));
        userNameStatus.setPreferredSize(new java.awt.Dimension(200, 20));
        PDisponibilidade.add(userNameStatus);
        PDisponibilidade.add(icon);

        PanelGeral.add(PDisponibilidade);

        Psenha.setLayout(new javax.swing.BoxLayout(Psenha, javax.swing.BoxLayout.LINE_AXIS));

        LabelSenhaInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelSenhaInfo.setText("Escolha uma senha:");
        LabelSenhaInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LabelSenhaInfo.setMaximumSize(new java.awt.Dimension(170, 14));
        LabelSenhaInfo.setMinimumSize(new java.awt.Dimension(170, 14));
        LabelSenhaInfo.setPreferredSize(new java.awt.Dimension(170, 14));
        Psenha.add(LabelSenhaInfo);

        senha.setMaximumSize(new java.awt.Dimension(230, 25));
        senha.setMinimumSize(new java.awt.Dimension(230, 25));
        senha.setPreferredSize(new java.awt.Dimension(230, 25));
        Psenha.add(senha);

        PanelGeral.add(Psenha);

        PrepeteSenha.setLayout(new javax.swing.BoxLayout(PrepeteSenha, javax.swing.BoxLayout.LINE_AXIS));

        LabeRepetirSenhaInfo.setText("Digite a senha novamente:");
        LabeRepetirSenhaInfo.setMaximumSize(new java.awt.Dimension(170, 14));
        LabeRepetirSenhaInfo.setMinimumSize(new java.awt.Dimension(170, 14));
        LabeRepetirSenhaInfo.setPreferredSize(new java.awt.Dimension(170, 14));
        PrepeteSenha.add(LabeRepetirSenhaInfo);

        repeteSenha.setMaximumSize(new java.awt.Dimension(230, 25));
        repeteSenha.setMinimumSize(new java.awt.Dimension(230, 25));
        repeteSenha.setPreferredSize(new java.awt.Dimension(230, 25));
        PrepeteSenha.add(repeteSenha);

        PanelGeral.add(PrepeteSenha);

        PanelButtons.setLayout(new javax.swing.BoxLayout(PanelButtons, javax.swing.BoxLayout.X_AXIS));

        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });
        PanelButtons.add(ButtonVoltar);

        ButtonCadastrar.setText("Cadastrar");
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });
        PanelButtons.add(ButtonCadastrar);

        PanelGeral.add(PanelButtons);

        getContentPane().add(PanelGeral);

        jPanel1.setMaximumSize(new java.awt.Dimension(25, 25));
        jPanel1.setMinimumSize(new java.awt.Dimension(25, 25));
        jPanel1.setPreferredSize(new java.awt.Dimension(25, 25));
        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_userActionPerformed

    /**
     * Quando o JtextField user perde o foco, ele dispara um FocusLost que
     * verifica se o nome de usuario digitado ja esta em uso no banco de dados
     *
     * @param evt
     */
    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        // TODO add your handling code here:
        if (!user.getText().equals("")) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("todosappPU");

            UsuarioDAO usuarioDAO = new UsuarioDAO(emf);

            Usuario usuario = usuarioDAO.findUsuarioUsername(user.getText());

            if (usuario == null) {

                icon.setIcon(iconTrue);
                userNameStatus.setText("Nome de usuario disponivel!");
                userNameStatus.setForeground(new java.awt.Color(0, 100, 51));

            } else {
                icon.setIcon(iconFalse);
                userNameStatus.setText("Nome de usuario indisponivel!");
                userNameStatus.setForeground(new java.awt.Color(255, 0, 0));
            }
            emf.close();
        }

    }//GEN-LAST:event_userFocusLost

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        // TODO add your handling code here:
        JFrame login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
        // TODO add your handling code here:
        if (!user.getText().equals("")) {
            if (criar()) {
                JFrameCriarUsuario criar = new JFrameCriarUsuario(img);
                criar.setVisible(true);
                dispose();
            }
        } else {
            JFrame frame = new JFrame("Alerta de criação de usuario");
            JOptionPane.showMessageDialog(frame, "Defina um nome de usuario valido!\nrecomendado mais de 3 caracteres");
        }

    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    public boolean criar() {

        JFrame frame = new JFrame("Alerta de criação de usuario");

        if (userNameStatus.equals("Nome de usuario indisponivel!")) {

            JOptionPane.showMessageDialog(frame, "Nome de usuario indisponivel!");

            return false;

        } else if (senha.getText().equals(repeteSenha.getText())) {

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("todosappPU");

            UsuarioDAO usuarioDAO = new UsuarioDAO(emf);

            Usuario usuario = new Usuario();

            usuario.setUsername(user.getText());
            usuario.setPassword(senha.getText());

            usuarioDAO.create(usuario);

            JOptionPane.showMessageDialog(frame, "Usuario cadastrado!");

            return true;

        } else {
            JOptionPane.showMessageDialog(frame, "Senha incorreta no segundo campo");
            return false;
        }

    }
    
    private Image img;
    private final Icon iconTrue;
    private final Icon iconFalse;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastrar;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JLabel LabeRepetirSenhaInfo;
    private javax.swing.JLabel LabelInfoFrame;
    private javax.swing.JLabel LabelSenhaInfo;
    private javax.swing.JLabel LabeluserInfo;
    private javax.swing.JPanel PDisponibilidade;
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelGeral;
    private javax.swing.JPanel PrepeteSenha;
    private javax.swing.JPanel Psenha;
    private javax.swing.JPanel Puser;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelInfoFrame;
    private javax.swing.JPasswordField repeteSenha;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userNameStatus;
    // End of variables declaration//GEN-END:variables
}
