/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.unifil.comp2028.todosapp.views;

/**
 *
 * @author Renato
 */
public class JFrameAdicionarCategoria extends javax.swing.JFrame {

    /**
     * Creates new form frameAdicionarCategoria
     */
    public JFrameAdicionarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espaceTop = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        PanelDescricao = new javax.swing.JPanel();
        LabelDescricao = new javax.swing.JLabel();
        TextFieldDescricao = new javax.swing.JTextField();
        espaceBot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(290, 117));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        espaceTop.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout espaceTopLayout = new javax.swing.GroupLayout(espaceTop);
        espaceTop.setLayout(espaceTopLayout);
        espaceTopLayout.setHorizontalGroup(
            espaceTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espaceTopLayout.setVerticalGroup(
            espaceTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(espaceTop);

        info.setMaximumSize(new java.awt.Dimension(250, 25));
        info.setMinimumSize(new java.awt.Dimension(250, 25));
        info.setPreferredSize(new java.awt.Dimension(250, 25));
        info.setLayout(new java.awt.BorderLayout());

        PanelDescricao.setLayout(new javax.swing.BoxLayout(PanelDescricao, javax.swing.BoxLayout.LINE_AXIS));

        LabelDescricao.setText("Descrição: ");
        PanelDescricao.add(LabelDescricao);
        PanelDescricao.add(TextFieldDescricao);

        info.add(PanelDescricao, java.awt.BorderLayout.CENTER);

        getContentPane().add(info);

        espaceBot.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout espaceBotLayout = new javax.swing.GroupLayout(espaceBot);
        espaceBot.setLayout(espaceBotLayout);
        espaceBotLayout.setHorizontalGroup(
            espaceBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        espaceBotLayout.setVerticalGroup(
            espaceBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(espaceBot);

        jPanel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 11)); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("cancelar");
        jPanel2.add(jButton1);

        jPanel5.setMaximumSize(new java.awt.Dimension(60, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jButton2.setText("adicionar");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdicionarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdicionarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDescricao;
    private javax.swing.JPanel PanelDescricao;
    private javax.swing.JTextField TextFieldDescricao;
    private javax.swing.JPanel espaceBot;
    private javax.swing.JPanel espaceTop;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
